# Generated by Django 2.0.3 on 2019-10-21 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(max_length=50)),
                ('n03_002', models.CharField(max_length=50)),
                ('n03_003', models.CharField(max_length=50)),
                ('n03_004', models.CharField(max_length=50)),
                ('n03_007', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
